name: release-please
on:
    push:
      branches:
        - main  
permissions:
    contents: write
    pull-requests: write
  
jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - name: Create Release
          id: release
          uses: google-github-actions/release-please-action@v3
          with:
            release-type: maven
            package-name: release-please-action
        - uses: peter-evans/enable-pull-request-automerge@v2
          with:
            pull-request-number: ${{fromJson(steps.release.outputs.pr).number}}
            merge-method: squash