name: release-please
on:
    push:
      branches:
        - main  
permissions:
    contents: write
    pull-requests: write
  
jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - name: Create Release
          id: release
          uses: google-github-actions/release-please-action@v3
          with:
            release-type: maven
            package-name: release-please-action
        - name: Show info
          run: echo ${{fromJson(steps.release.outputs.pr).number}}    